modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Tieso2001/BoneAppleTea/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/boneappletea"
authors="Tieso2001"

[[mods]]
    modId="boneappletea"
    version="${file.jarVersion}"
    displayName="Bone Apple Tea"
    description='''
    More options for food and farming'''

[[dependencies.boneappletea]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.boneappletea]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"